### ISSUE TITLE
Sort the list of books by author and/or title

### ISSUE THREAD

**Issue by Nnamdikeshi** [Nnamdikeshi/book_wishlist#7]
Currently books are sorted by ID, which correlates to date added; as that is how they are created. 

Would it be more user-friendly to sort by author, and/or title, or give the user a choice?  Implement what you think would be most useful.

**Comment by pi6220na** [comment]
Added a new menu item, choice #5, to sort the book list (read, and unread) on either the Title or Author. Other sort criteria can easily be accommodated as the user desires. - Jeremy 1/20/2018
